### ISSUE TITLE
Audit 2.0 rules for deprecation or inclusion in 3.0

### ISSUE THREAD

**Issue by klebba** [Netflix/eslint-config-netflix#19]
### 2.0 formatting rules removed in 3.0 ([deprecated by ESLint](https://eslint.org/blog/2023/10/deprecating-formatting-rules/))

- array-bracket-spacing
- comma-style
- eol-last
- generator-star-spacing
- indent
- jsx-quotes
- key-spacing
- no-extra-parens
- no-multi-spaces
- no-multiple-empty-lines
- object-curly-spacing
- quote-props
- semi-spacing
- space-before-blocks
- space-before-function-paren
- template-curly-spacing
- yield-star-spacing

### 2.0 rules now covered by `eslint:recommended` in 3.0
- no-const-assign
- no-debugger
- no-empty-pattern
- no-fallthrough (removed `warning` override, now `error` per `eslint:recommended`)
- no-func-assign
- no-irregular-whitespace
- no-prototype-builtins (removed `warning` override, now `error` per `eslint:recommended`)
- no-redeclare
- no-self-assign
- no-with
- valid-typeof

### 2.0 rules carried forward to 3.0
- array-callback-return
- comma-dangle (deprecated, will remove in 4.0)
- curly (deprecated, will remove in 4.0)
- dot-notation
- eqeqeq
- guard-for-in
- no-bitwise
- no-caller
- no-eval
- no-extend-native
- no-loop-func
- no-proto
- no-script-url
- no-sequences
- no-shadow
- no-undef
- no-unused-expressions
- no-unused-vars
- no-var
- prefer-arrow-callback
- prefer-const
- quotes (deprecated, will remove in 4.0)
- semi (deprecated, will remove in 4.0)

### 2.0 rules removed in 3.0 (rationale below)
- camelcase
- class-methods-use-this
- new-cap
- no-empty
- no-empty-function
- no-iterator
- no-lone-blocks
- no-multi-str
- no-new
- no-plusplus
- no-template-curly-in-string
- no-underscore-dangle
- no-useless-constructor
- no-useless-rename
- prefer-rest-params
- prefer-spread
- prefer-template
- strict

### 3.0 rules added
- [js.configs.recommended.rules](https://github.com/eslint/eslint/blob/main/packages/js/src/configs/eslint-recommended.js)
- no-console
- no-constant-binary-expression
- no-undef-init
- prefer-object-has-own

**Comment by klebba** [comment]
TODO:
- `no-prototype-builtins` is now covered by the recommended rules and can be removed from the extended config.

**Comment by klebba** [comment]
Note:
- no-fallthrough
- no-prototype-builtins

These may have been relaxed from error to warning in order to ensure former versions of ESLint would not bomb out in their occurrence (vs continue parsing)

**Comment by klebba** [comment]
Perhaps consider https://typescript-eslint.io/rules/no-require-imports/
- Pro: require() is a non-standard holding back the web
- Con: this rule would aggressively warn about something that can't be changed in most developer scenarios

**Comment by klebba** [comment]
@theengineear I know it's a lot to review but there's no specific urgency here. I'm looking for a cross-check on my disposition of the rules to be dis/included in 3.0 — my hope is to slim this thing down and not leave anyone in the lurch who wants to upgrade

**Comment by theengineear** [comment]
Going to just mark this one-by-one and keep returning to this comment as I go:

⌛ ➖ [array-callback-return](https://eslint.org/docs/latest/rules/array-callback-return)
⌛ ➖ [camelcase](https://eslint.org/docs/latest/rules/camelcase)
⌛ ➖ [class-methods-use-this](https://eslint.org/docs/latest/rules/class-methods-use-this)
⌛ ➖ [curly](https://eslint.org/docs/latest/rules/curly)
⌛ ➖ [dot-notation](https://eslint.org/docs/latest/rules/dot-notation)
⌛ ➕ [guard-for-in](https://eslint.org/docs/latest/rules/guard-for-in)
⌛ ➖ [new-cap](https://eslint.org/docs/latest/rules/new-cap)
⌛ ➖ [no-bitwise](https://eslint.org/docs/latest/rules/no-bitwise)
⌛ ➕ [no-caller](https://eslint.org/docs/latest/rules/no-caller)
⌛ ➖ [no-empty](https://eslint.org/docs/latest/rules/no-empty)
⌛ ➖ [no-empty-function](https://eslint.org/docs/latest/rules/no-empty-function)
👍 ➕ [no-eval](https://eslint.org/docs/latest/rules/no-eval)
⌛ ➕ [no-extend-native](https://eslint.org/docs/latest/rules/no-extend-native)
⌛ ➖ [no-iterator](https://eslint.org/docs/latest/rules/no-iterator)
⌛ ➖ [no-lone-blocks](https://eslint.org/docs/latest/rules/no-lone-blocks)
⌛ ➕ [no-loop-func](https://eslint.org/docs/latest/rules/no-loop-func)
⌛ ➖ [no-multi-str](https://eslint.org/docs/latest/rules/no-multi-str)
⌛ ➖ [no-new](https://eslint.org/docs/latest/rules/no-new)
⌛ ➖ [no-plusplus](https://eslint.org/docs/latest/rules/no-plusplus)
⌛ ➕ [no-proto](https://eslint.org/docs/latest/rules/no-proto)
⌛ ➕ [no-script-url](https://eslint.org/docs/latest/rules/no-script-url)
⌛ ➖ [no-sequences](https://eslint.org/docs/latest/rules/no-sequences)
⌛ ➖ [no-template-curly-in-string](https://eslint.org/docs/latest/rules/no-template-curly-in-string)
⌛ ➖ [no-underscore-dangle](https://eslint.org/docs/latest/rules/no-underscore-dangle)
⌛ ➕ [no-unused-expressions](https://eslint.org/docs/latest/rules/no-unused-expressions)
⌛ ➖ [no-useless-constructor](https://eslint.org/docs/latest/rules/no-useless-constructor)
👍 ➖ [no-useless-rename](https://eslint.org/docs/latest/rules/no-useless-rename)
⌛ ➖ [prefer-rest-params](https://eslint.org/docs/latest/rules/prefer-rest-params)
⌛ ➖ [prefer-spread](https://eslint.org/docs/latest/rules/prefer-spread)
⌛ ➖ [prefer-template](https://eslint.org/docs/latest/rules/prefer-template)
⌛ ➖ [strict](https://eslint.org/docs/latest/rules/strict)

**Comment by theengineear** [comment]
@klebba — That was a lot of documentation reading! I mostly agree with your sentiment (thanks for writing in a way that was easy to review, by the way!). There are just a handful of things that I _may_ disagree on.

**Comment by klebba** [comment]
Thanks for the review; I'll incorporate your feedback / respond soon and ping back here

**Comment by theengineear** [comment]
Sounds good to me @klebba! I agree with your summaries above 👌

**Comment by klebba** [comment]
Addressed by #21
