### ISSUE TITLE
array-callback-return warnings

### ISSUE THREAD

**Issue by klebba** [Netflix/eslint-config-netflix#31]
See: https://eslint.org/docs/latest/rules/array-callback-return

With the rule enabled, this causes a warning:

```
const index = list.findLastIndex(candidateId => {
  const candidate = input[candidateId];
  if (candidate.ok === true) {
    return true;
  }
});
```

Developers must instead rewrite like this:

```
const index = list.findLastIndex(candidateId => {
  const candidate = input[candidateId];
  if (candidate.ok === true) {
    return true;
  }
  return undefined;
});
```

Musings: Warning developers to add `return undefined;` to conclude some function calls and not others is inconsistent. Requiring developers to add `return undefined;` at all seems superfluous.

In #19 we said:

> using these methods carry certain semantics. If you don’t want to actually create an object, different methods exist with the appropriate semantics.

Is the rule doing what we expect?

**Comment by theengineear** [comment]
**IMO, let’s ditch it.** I wanted to keep it to warn when we _don’t ever return anything_ — but it’s way too noisy in that it enforces that you _always return something_. It’s perfectly valid to implicitly return `undefined` in these cases.
